#################################################################################
#
#  Title:     Estimating causal effects in observational studies for survival 
#             data with a cure fraction using propensity score adjustment
#
#  Script:    MSE_table1&2.R
#
#  Authors:   Ziwen Wang | Chenguang Wang | Xiaoguang Wang
#
#  Purpose:   Create all results in Tables 1 and 2 in the paper,
#             output the results of Table 1 on lines 440-441, Table 2 on lines 448-449
#             without manual intervention
#
#  Output Results: 
#             PB: the mean relative bias of the estimates. 
#             SD: the sample standard deviation. 
#             SE: the average of the 500 estimated standard errors. 
#             MSE: the mean squared error.
##################################################################################

## ===============================================================================
#  Remark:  To save time, intermediate results have been saved in the folder
#           "MSE_intermediate_results/..":
#           The saved results can be loaded with load().
#           Example: load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE20_PSBeran.RData")
#  
#           The results can also be generated by running the code in "XXX_mse.R" in the folder
            "Methods_MSE/.."
## ================================================================================

#setwd("~/Code and data")
source("functions/function_definitions.R")
load("true/True_value.RData")

nn <- 500          # sample size
repli <- 500       # the number of replications

##======================================================================================================
## Weak association summary
##======================================================================================================

#======= alpha0 = 0, PE = 20%, alpha11=beta11=log(2) weak association ==================================

summ_true <- summ_weak_alpha0[c(1,4)]  # true value
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE20_Beran.RData")
Results_mse0_PE20_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE20_MPSBeran.RData")
Results_mse0_PE20_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE20_PSBeran.RData")
Results_mse0_PE20_psberan <- Get_MSE()

#======= alpha0 = 0, PE = 35%, alpha11=beta11=log(2) weak association ==================================

load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE35_Beran.RData")
Results_mse0_PE35_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE35_MPSBeran.RData")
Results_mse0_PE35_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE35_PSBeran.RData")
Results_mse0_PE35_psberan <- Get_MSE()

#======= alpha0 = 0, PE = 50%, alpha11=beta11=log(2) weak association ==================================

load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE50_Beran.RData")
Results_mse0_PE50_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE50_MPSBeran.RData")
Results_mse0_PE50_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp0_PE50_PSBeran.RData")
Results_mse0_PE50_psberan <- Get_MSE()

#======= alpha0 = 0.5, PE = 20%, alpha11=beta11=log(2) weak association ==================================

summ_true <- summ_weak_alpha05[c(1,4)]  # true value
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE20_Beran.RData")
Results_mse05_PE20_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE20_MPSBeran.RData")
Results_mse05_PE20_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE20_PSBeran.RData")
Results_mse05_PE20_psberan <- Get_MSE()

#======= alpha0 = 0.5, PE = 35%, alpha11=beta11=log(2) weak association ==================================

load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE35_Beran.RData")
Results_mse05_PE35_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE35_MPSBeran.RData")
Results_mse05_PE35_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE35_PSBeran.RData")
Results_mse05_PE35_psberan <- Get_MSE()

#======= alpha0 = 0.5, PE = 50%, alpha11=beta11=log(2) weak association ==================================

load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE50_Beran.RData")
Results_mse05_PE50_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE50_MPSBeran.RData")
Results_mse05_PE50_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp05_PE50_PSBeran.RData")
Results_mse05_PE50_psberan <- Get_MSE()

#======= alpha0 = 1, PE = 20%, alpha11=beta11=log(2) weak association ==================================

summ_true <- summ_weak_alpha1[c(1,4)]  # true value
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE20_Beran.RData")
Results_mse1_PE20_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE20_MPSBeran.RData")
Results_mse1_PE20_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE20_PSBeran.RData")
Results_mse1_PE20_psberan <- Get_MSE()

#======= alpha0 = 1, PE = 35%, alpha11=beta11=log(2) weak association ==================================

load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE35_Beran.RData")
Results_mse1_PE35_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE35_MPSBeran.RData")
Results_mse1_PE35_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE35_PSBeran.RData")
Results_mse1_PE35_psberan <- Get_MSE()

#======= alpha0 = 1, PE = 50%, alpha11=beta11=log(2) weak association ==================================

load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE50_Beran.RData")
Results_mse1_PE50_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE50_MPSBeran.RData")
Results_mse1_PE50_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/weak/MSE_ACE_SPCEcure_weak_alp1_PE50_PSBeran.RData")
Results_mse1_PE50_psberan <- Get_MSE()

##====== RACE for Native method, PHMC, and PSKM method ======================================================

load("simulation_study/MSE_intermediate_results/weak/Native_mse_weak.RData")
race_native0 <- c(Results_mse_alp0$PE20[1,4:6], Results_mse_alp0$PE35[1,4:6], Results_mse_alp0$PE50[1,4:6])
race_native05 <- c(Results_mse_alp05$PE20[1,4:6], Results_mse_alp05$PE35[1,4:6], Results_mse_alp05$PE50[1,4:6])
race_native1 <- c(Results_mse_alp1$PE20[1,4:6], Results_mse_alp1$PE35[1,4:6], Results_mse_alp1$PE50[1,4:6])
spce_native0 <- c(Results_mse_alp0$PE20[2,4:6], Results_mse_alp0$PE35[2,4:6], Results_mse_alp0$PE50[2,4:6])
spce_native05 <- c(Results_mse_alp05$PE20[2,4:6], Results_mse_alp05$PE35[2,4:6], Results_mse_alp05$PE50[2,4:6])
spce_native1 <- c(Results_mse_alp1$PE20[2,4:6], Results_mse_alp1$PE35[2,4:6], Results_mse_alp1$PE50[2,4:6])

load("simulation_study/MSE_intermediate_results/weak/PHMC_mse_weak.RData")
race_phmc0 <- c(Results_mse_alp0$PE20[1,4:6], Results_mse_alp0$PE35[1,4:6], Results_mse_alp0$PE50[1,4:6])
race_phmc05 <- c(Results_mse_alp05$PE20[1,4:6], Results_mse_alp05$PE35[1,4:6], Results_mse_alp05$PE50[1,4:6])
race_phmc1 <- c(Results_mse_alp1$PE20[1,4:6], Results_mse_alp1$PE35[1,4:6], Results_mse_alp1$PE50[1,4:6])
spce_phmc0 <- c(Results_mse_alp0$PE20[2,4:6], Results_mse_alp0$PE35[2,4:6], Results_mse_alp0$PE50[2,4:6])
spce_phmc05 <- c(Results_mse_alp05$PE20[2,4:6], Results_mse_alp05$PE35[2,4:6], Results_mse_alp05$PE50[2,4:6])
spce_phmc1 <- c(Results_mse_alp1$PE20[2,4:6], Results_mse_alp1$PE35[2,4:6], Results_mse_alp1$PE50[2,4:6])

load("simulation_study/MSE_intermediate_results/weak/PSKM_mse_weak.RData")
race_pskm0 <- c(Results_mse_alp0$PE20[1,4:6], Results_mse_alp0$PE35[1,4:6], Results_mse_alp0$PE50[1,4:6])
race_pskm05 <- c(Results_mse_alp05$PE20[1,4:6], Results_mse_alp05$PE35[1,4:6], Results_mse_alp05$PE50[1,4:6])
race_pskm1 <- c(Results_mse_alp1$PE20[1,4:6], Results_mse_alp1$PE35[1,4:6], Results_mse_alp1$PE50[1,4:6])
spce_pskm0 <- c(Results_mse_alp0$PE20[2,4:6], Results_mse_alp0$PE35[2,4:6], Results_mse_alp0$PE50[2,4:6])
spce_pskm05 <- c(Results_mse_alp05$PE20[2,4:6], Results_mse_alp05$PE35[2,4:6], Results_mse_alp05$PE50[2,4:6])
spce_pskm1 <- c(Results_mse_alp1$PE20[2,4:6], Results_mse_alp1$PE35[2,4:6], Results_mse_alp1$PE50[2,4:6])

race_beran0 <- c(Results_mse0_PE20_beran$Summary_summ[1,4:6], 
                 Results_mse0_PE35_beran$Summary_summ[1,4:6],
                 Results_mse0_PE50_beran$Summary_summ[1,4:6])
race_mpsberan0 <- c(Results_mse0_PE20_mpsberan$Summary_summ[1,4:6],
                    Results_mse0_PE35_mpsberan$Summary_summ[1,4:6],
                    Results_mse0_PE50_mpsberan$Summary_summ[1,4:6])
race_psberan0 <- c(Results_mse0_PE20_psberan$Summary_summ[1,4:6],
                   Results_mse0_PE35_psberan$Summary_summ[1,4:6],
                   Results_mse0_PE50_psberan$Summary_summ[1,4:6])

race_beran05 <- c(Results_mse05_PE20_beran$Summary_summ[1,4:6],
                  Results_mse05_PE35_beran$Summary_summ[1,4:6],
                  Results_mse05_PE50_beran$Summary_summ[1,4:6])
race_mpsberan05 <- c(Results_mse05_PE20_mpsberan$Summary_summ[1,4:6],
                     Results_mse05_PE35_mpsberan$Summary_summ[1,4:6],
                     Results_mse05_PE50_mpsberan$Summary_summ[1,4:6])
race_psberan05 <- c(Results_mse05_PE20_psberan$Summary_summ[1,4:6],
                    Results_mse05_PE35_psberan$Summary_summ[1,4:6],
                    Results_mse05_PE50_psberan$Summary_summ[1,4:6])

race_beran1 <- c(Results_mse1_PE20_beran$Summary_summ[1,4:6],
                 Results_mse1_PE35_beran$Summary_summ[1,4:6],
                 Results_mse1_PE50_beran$Summary_summ[1,4:6])
race_mpsberan1 <- c(Results_mse1_PE20_mpsberan$Summary_summ[1,4:6],
                    Results_mse1_PE35_mpsberan$Summary_summ[1,4:6],
                    Results_mse1_PE50_mpsberan$Summary_summ[1,4:6])
race_psberan1 <- c(Results_mse1_PE20_psberan$Summary_summ[1,4:6],
                   Results_mse1_PE35_psberan$Summary_summ[1,4:6],
                   Results_mse1_PE50_psberan$Summary_summ[1,4:6])


spce_beran0 <- c(Results_mse0_PE20_beran$Summary_summ[2,4:6], 
                 Results_mse0_PE35_beran$Summary_summ[2,4:6],
                 Results_mse0_PE50_beran$Summary_summ[2,4:6])
spce_mpsberan0 <- c(Results_mse0_PE20_mpsberan$Summary_summ[2,4:6],
                    Results_mse0_PE35_mpsberan$Summary_summ[2,4:6],
                    Results_mse0_PE50_mpsberan$Summary_summ[2,4:6])
spce_psberan0 <- c(Results_mse0_PE20_psberan$Summary_summ[2,4:6],
                   Results_mse0_PE35_psberan$Summary_summ[2,4:6],
                   Results_mse0_PE50_psberan$Summary_summ[2,4:6])

spce_beran05 <- c(Results_mse05_PE20_beran$Summary_summ[2,4:6],
                  Results_mse05_PE35_beran$Summary_summ[2,4:6],
                  Results_mse05_PE50_beran$Summary_summ[2,4:6])
spce_mpsberan05 <- c(Results_mse05_PE20_mpsberan$Summary_summ[2,4:6],
                     Results_mse05_PE35_mpsberan$Summary_summ[2,4:6],
                     Results_mse05_PE50_mpsberan$Summary_summ[2,4:6])
spce_psberan05 <- c(Results_mse05_PE20_psberan$Summary_summ[2,4:6],
                    Results_mse05_PE35_psberan$Summary_summ[2,4:6],
                    Results_mse05_PE50_psberan$Summary_summ[2,4:6])

spce_beran1 <- c(Results_mse1_PE20_beran$Summary_summ[2,4:6],
                 Results_mse1_PE35_beran$Summary_summ[2,4:6],
                 Results_mse1_PE50_beran$Summary_summ[2,4:6])
spce_mpsberan1 <- c(Results_mse1_PE20_mpsberan$Summary_summ[2,4:6],
                    Results_mse1_PE35_mpsberan$Summary_summ[2,4:6],
                    Results_mse1_PE50_mpsberan$Summary_summ[2,4:6])
spce_psberan1 <- c(Results_mse1_PE20_psberan$Summary_summ[2,4:6],
                   Results_mse1_PE35_psberan$Summary_summ[2,4:6],
                   Results_mse1_PE50_psberan$Summary_summ[2,4:6])

##------------------------------------------------------------------------------
Summary_RACE0 <- rbind(race_native0, race_phmc0,  race_beran0,
                       race_pskm0, race_mpsberan0, race_psberan0)
Summary_RACE05 <- rbind(race_native05, race_phmc05,  race_beran05,
                        race_pskm05, race_mpsberan05, race_psberan05)
Summary_RACE1 <- rbind(race_native1, race_phmc1,  race_beran1,
                       race_pskm1, race_mpsberan1, race_psberan1)
#row_name <- c("Native", "PHMC", "Beran", "PS_KM", "MPS_Beran", "PS_Beran")
Summary_RACE_weak <- list(Summary_RACE0 = Summary_RACE0, 
                          Summary_RACE05 = Summary_RACE05,
                          Summary_RACE1 = Summary_RACE1)


Summary_SPCE0 <- rbind(spce_native0, spce_phmc0,  spce_beran0,
                       spce_pskm0, spce_mpsberan0, spce_psberan0)
Summary_SPCE05 <- rbind(spce_native05, spce_phmc05,  spce_beran05,
                        spce_pskm05, spce_mpsberan05, spce_psberan05)
Summary_SPCE1 <- rbind(spce_native1, spce_phmc1,  spce_beran1,
                       spce_pskm1, spce_mpsberan1, spce_psberan1)
#row_name <- c("Native", "PHMC", "Beran", "PS_KM", "MPS_Beran", "PS_Beran")
Summary_SPCE_weak <- list(Summary_SPCE0 = Summary_SPCE0, 
                          Summary_SPCE05 = Summary_SPCE05,
                          Summary_SPCE1 = Summary_SPCE1)


##======================================================================================================
## Strong association summary
##======================================================================================================
source("functions/function_definitions.R")
load("true/True_value.RData")

#======= alpha0 = 0, PE = 20%, alpha11=beta11=log(2) strong association ==================================
summ_true <- summ_strong_alpha0[c(1,4)]  # true value
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE20_Beran.RData")
Results_mse0_PE20_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE20_MPSBeran.RData")
Results_mse0_PE20_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE20_PSBeran.RData")
Results_mse0_PE20_psberan <- Get_MSE()

#======= alpha0 = 0, PE = 35%, alpha11=beta11=log(2) strong association ==================================

load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE35_Beran.RData")
Results_mse0_PE35_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE35_MPSBeran.RData")
Results_mse0_PE35_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE35_PSBeran.RData")
Results_mse0_PE35_psberan <- Get_MSE()

#======= alpha0 = 0, PE = 50%, alpha11=beta11=log(2) strong association ==================================

load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE50_Beran.RData")
Results_mse0_PE50_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE50_MPSBeran.RData")
Results_mse0_PE50_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp0_PE50_PSBeran.RData")
Results_mse0_PE50_psberan <- Get_MSE()

#======= alpha0 = 0.5, PE = 20%, alpha11=beta11=log(2) strong association ==================================

summ_true <- summ_strong_alpha05[c(1,4)]  # true value
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE20_Beran.RData")
Results_mse05_PE20_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE20_MPSBeran.RData")
Results_mse05_PE20_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE20_PSBeran.RData")
Results_mse05_PE20_psberan <- Get_MSE()

#======= alpha0 = 0.5, PE = 35%, alpha11=beta11=log(2) strong association ==================================

load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE35_Beran.RData")
Results_mse05_PE35_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE35_MPSBeran.RData")
Results_mse05_PE35_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE35_PSBeran.RData")
Results_mse05_PE35_psberan <- Get_MSE()

#======= alpha0 = 0.5, PE = 50%, alpha11=beta11=log(2) strong association ==================================

load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE50_Beran.RData")
Results_mse05_PE50_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE50_MPSBeran.RData")
Results_mse05_PE50_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp05_PE50_PSBeran.RData")
Results_mse05_PE50_psberan <- Get_MSE()

#======= alpha0 = 1, PE = 20%, alpha11=beta11=log(2) strong association =====================================

summ_true <- summ_strong_alpha1[c(1,4)]  # true value
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE20_Beran.RData")
Results_mse1_PE20_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE20_MPSBeran.RData")
Results_mse1_PE20_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE20_PSBeran.RData")
Results_mse1_PE20_psberan <- Get_MSE()

#======= alpha0 = 1, PE = 35%, alpha11=beta11=log(2) strong association ==================================

load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE35_Beran.RData")
Results_mse1_PE35_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE35_MPSBeran.RData")
Results_mse1_PE35_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE35_PSBeran.RData")
Results_mse1_PE35_psberan <- Get_MSE()

#======= alpha0 = 1, PE = 50%, alpha11=beta11=log(2) strong association ==================================

load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE50_Beran.RData")
Results_mse1_PE50_beran <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE50_MPSBeran.RData")
Results_mse1_PE50_mpsberan <- Get_MSE()
load("simulation_study/MSE_intermediate_results/strong/MSE_ACE_SPCEcure_strong_alp1_PE50_PSBeran.RData")
Results_mse1_PE50_psberan <- Get_MSE()

##====== RACE for Native method, PHMC, and PSKM method ======================================================

load("simulation_study/MSE_intermediate_results/strong/Native_mse_strong.RData")
race_native0 <- c(Results_mse_alp0$PE20[1,4:6], Results_mse_alp0$PE35[1,4:6], Results_mse_alp0$PE50[1,4:6])
race_native05 <- c(Results_mse_alp05$PE20[1,4:6], Results_mse_alp05$PE35[1,4:6], Results_mse_alp05$PE50[1,4:6])
race_native1 <- c(Results_mse_alp1$PE20[1,4:6], Results_mse_alp1$PE35[1,4:6], Results_mse_alp1$PE50[1,4:6])
spce_native0 <- c(Results_mse_alp0$PE20[2,4:6], Results_mse_alp0$PE35[2,4:6], Results_mse_alp0$PE50[2,4:6])
spce_native05 <- c(Results_mse_alp05$PE20[2,4:6], Results_mse_alp05$PE35[2,4:6], Results_mse_alp05$PE50[2,4:6])
spce_native1 <- c(Results_mse_alp1$PE20[2,4:6], Results_mse_alp1$PE35[2,4:6], Results_mse_alp1$PE50[2,4:6])

load("simulation_study/MSE_intermediate_results/strong/PHMC_mse_strong.RData")
race_phmc0 <- c(Results_mse_alp0$PE20[1,4:6], Results_mse_alp0$PE35[1,4:6], Results_mse_alp0$PE50[1,4:6])
race_phmc05 <- c(Results_mse_alp05$PE20[1,4:6], Results_mse_alp05$PE35[1,4:6], Results_mse_alp05$PE50[1,4:6])
race_phmc1 <- c(Results_mse_alp1$PE20[1,4:6], Results_mse_alp1$PE35[1,4:6], Results_mse_alp1$PE50[1,4:6])
spce_phmc0 <- c(Results_mse_alp0$PE20[2,4:6], Results_mse_alp0$PE35[2,4:6], Results_mse_alp0$PE50[2,4:6])
spce_phmc05 <- c(Results_mse_alp05$PE20[2,4:6], Results_mse_alp05$PE35[2,4:6], Results_mse_alp05$PE50[2,4:6])
spce_phmc1 <- c(Results_mse_alp1$PE20[2,4:6], Results_mse_alp1$PE35[2,4:6], Results_mse_alp1$PE50[2,4:6])

load("simulation_study/MSE_intermediate_results/strong/PSKM_mse_strong.RData")
race_pskm0 <- c(Results_mse_alp0$PE20[1,4:6], Results_mse_alp0$PE35[1,4:6], Results_mse_alp0$PE50[1,4:6])
race_pskm05 <- c(Results_mse_alp05$PE20[1,4:6], Results_mse_alp05$PE35[1,4:6], Results_mse_alp05$PE50[1,4:6])
race_pskm1 <- c(Results_mse_alp1$PE20[1,4:6], Results_mse_alp1$PE35[1,4:6], Results_mse_alp1$PE50[1,4:6])
spce_pskm0 <- c(Results_mse_alp0$PE20[2,4:6], Results_mse_alp0$PE35[2,4:6], Results_mse_alp0$PE50[2,4:6])
spce_pskm05 <- c(Results_mse_alp05$PE20[2,4:6], Results_mse_alp05$PE35[2,4:6], Results_mse_alp05$PE50[2,4:6])
spce_pskm1 <- c(Results_mse_alp1$PE20[2,4:6], Results_mse_alp1$PE35[2,4:6], Results_mse_alp1$PE50[2,4:6])

race_beran0 <- c(Results_mse0_PE20_beran$Summary_summ[1,4:6], 
                 Results_mse0_PE35_beran$Summary_summ[1,4:6],
                 Results_mse0_PE50_beran$Summary_summ[1,4:6])
race_mpsberan0 <- c(Results_mse0_PE20_mpsberan$Summary_summ[1,4:6],
                    Results_mse0_PE35_mpsberan$Summary_summ[1,4:6],
                    Results_mse0_PE50_mpsberan$Summary_summ[1,4:6])
race_psberan0 <- c(Results_mse0_PE20_psberan$Summary_summ[1,4:6],
                   Results_mse0_PE35_psberan$Summary_summ[1,4:6],
                   Results_mse0_PE50_psberan$Summary_summ[1,4:6])

race_beran05 <- c(Results_mse05_PE20_beran$Summary_summ[1,4:6],
                  Results_mse05_PE35_beran$Summary_summ[1,4:6],
                  Results_mse05_PE50_beran$Summary_summ[1,4:6])
race_mpsberan05 <- c(Results_mse05_PE20_mpsberan$Summary_summ[1,4:6],
                     Results_mse05_PE35_mpsberan$Summary_summ[1,4:6],
                     Results_mse05_PE50_mpsberan$Summary_summ[1,4:6])
race_psberan05 <- c(Results_mse05_PE20_psberan$Summary_summ[1,4:6],
                    Results_mse05_PE35_psberan$Summary_summ[1,4:6],
                    Results_mse05_PE50_psberan$Summary_summ[1,4:6])

race_beran1 <- c(Results_mse1_PE20_beran$Summary_summ[1,4:6],
                 Results_mse1_PE35_beran$Summary_summ[1,4:6],
                 Results_mse1_PE50_beran$Summary_summ[1,4:6])
race_mpsberan1 <- c(Results_mse1_PE20_mpsberan$Summary_summ[1,4:6],
                    Results_mse1_PE35_mpsberan$Summary_summ[1,4:6],
                    Results_mse1_PE50_mpsberan$Summary_summ[1,4:6])
race_psberan1 <- c(Results_mse1_PE20_psberan$Summary_summ[1,4:6],
                   Results_mse1_PE35_psberan$Summary_summ[1,4:6],
                   Results_mse1_PE50_psberan$Summary_summ[1,4:6])

spce_beran0 <- c(Results_mse0_PE20_beran$Summary_summ[2,4:6], 
                 Results_mse0_PE35_beran$Summary_summ[2,4:6],
                 Results_mse0_PE50_beran$Summary_summ[2,4:6])
spce_mpsberan0 <- c(Results_mse0_PE20_mpsberan$Summary_summ[2,4:6],
                    Results_mse0_PE35_mpsberan$Summary_summ[2,4:6],
                    Results_mse0_PE50_mpsberan$Summary_summ[2,4:6])
spce_psberan0 <- c(Results_mse0_PE20_psberan$Summary_summ[2,4:6],
                   Results_mse0_PE35_psberan$Summary_summ[2,4:6],
                   Results_mse0_PE50_psberan$Summary_summ[2,4:6])

spce_beran05 <- c(Results_mse05_PE20_beran$Summary_summ[2,4:6],
                  Results_mse05_PE35_beran$Summary_summ[2,4:6],
                  Results_mse05_PE50_beran$Summary_summ[2,4:6])
spce_mpsberan05 <- c(Results_mse05_PE20_mpsberan$Summary_summ[2,4:6],
                     Results_mse05_PE35_mpsberan$Summary_summ[2,4:6],
                     Results_mse05_PE50_mpsberan$Summary_summ[2,4:6])
spce_psberan05 <- c(Results_mse05_PE20_psberan$Summary_summ[2,4:6],
                    Results_mse05_PE35_psberan$Summary_summ[2,4:6],
                    Results_mse05_PE50_psberan$Summary_summ[2,4:6])

spce_beran1 <- c(Results_mse1_PE20_beran$Summary_summ[2,4:6],
                 Results_mse1_PE35_beran$Summary_summ[2,4:6],
                 Results_mse1_PE50_beran$Summary_summ[2,4:6])
spce_mpsberan1 <- c(Results_mse1_PE20_mpsberan$Summary_summ[2,4:6],
                    Results_mse1_PE35_mpsberan$Summary_summ[2,4:6],
                    Results_mse1_PE50_mpsberan$Summary_summ[2,4:6])
spce_psberan1 <- c(Results_mse1_PE20_psberan$Summary_summ[2,4:6],
                   Results_mse1_PE35_psberan$Summary_summ[2,4:6],
                   Results_mse1_PE50_psberan$Summary_summ[2,4:6])

##-----------------------------------------------------------------------------
Summary_RACE0 <- rbind(race_native0, race_phmc0,  race_beran0,
                       race_pskm0, race_mpsberan0, race_psberan0)
Summary_RACE05 <- rbind(race_native05, race_phmc05,  race_beran05,
                        race_pskm05, race_mpsberan05, race_psberan05)
Summary_RACE1 <- rbind(race_native1, race_phmc1,  race_beran1,
                       race_pskm1, race_mpsberan1, race_psberan1)
#row_name <- c("Native", "PHMC", "Beran", "PS_KM", "MPS_Beran", "PS_Beran")
Summary_RACE_strong <- list(Summary_RACE0 = Summary_RACE0, 
                            Summary_RACE05 = Summary_RACE05,
                            Summary_RACE1 = Summary_RACE1)


Summary_SPCE0 <- rbind(spce_native0, spce_phmc0,  spce_beran0,
                       spce_pskm0, spce_mpsberan0, spce_psberan0)
Summary_SPCE05 <- rbind(spce_native05, spce_phmc05,  spce_beran05,
                        spce_pskm05, spce_mpsberan05, spce_psberan05)
Summary_SPCE1 <- rbind(spce_native1, spce_phmc1,  spce_beran1,
                       spce_pskm1, spce_mpsberan1, spce_psberan1)
#row_name <- c("Native", "PHMC", "Beran", "PS_KM", "MPS_Beran", "PS_Beran")
Summary_SPCE_strong <- list(Summary_SPCE0 = Summary_SPCE0, 
                            Summary_SPCE05 = Summary_SPCE05, 
                            Summary_SPCE1 = Summary_SPCE1)

## =============================================================================
## Results Summary: Table 1  
## =============================================================================
print(Summary_RACE_weak)
print(Summary_RACE_strong)

#save(Summary_RACE_weak, Summary_RACE_strong, file = "simulation_study/results/table1.Rdata")

## =============================================================================
## Results Summary: Table 2  
## =============================================================================
print(Summary_SPCE_weak)
print(Summary_SPCE_strong)

#save(Summary_SPCE_weak, Summary_SPCE_strong, file = "simulation_study/results/table2.RData")
