###############################################################################
#
#  Title:       Estimating causal effects in observational studies for survival 
#               data with a cure fraction using propensity score adjustment
#
#  Script:      table4.R
#
#  Authors:     Ziwen Wang | Chenguang Wang | Xiaoguang Wang
#
#  Purpose:     Create all results of Table 4 of the paper, 
#               output the results of Table 4 on line 192 in this script,
#               without manual intervention
# 
###############################################################################

## =============================================================================
#  Remark: To save time, the results for all settings have been saved in the folder "bootstrap_intermediate_results/..":
#          Table 4 mainly shows the results under the strong relationship.
#          The saved results can be loaded with load(). 
#          Example: load("boots_intermediate_results/boots_strong_alp0_PE20_PSBeran_n150.RData") 
#
#          The results can also be generated by running the code in "PSBeran_boots.R" 
#          in the folder "simulation_study/PSBeran_bootstrap"
#          (The script for one setting may take ~72 hours to execute)
#
#  Output Results: 
#  PB: the mean relative bias of the estimates. 
#  SD: the sample standard deviation. 
#  SE: the average of the 500 estimated standard errors. 
#  CP:  the 95% empirical coverage probability (based on qnorm(0.975))
#  CP2: the 95% empirical coverage probability. (based on 1.96),  about the same as the CP value
#  MSE: the mean squared error.
## =============================================================================

# Source functions and load true value 
source("functions/function_definitions.R")
load("true/True_value.RData")

p <- 4
repli <- 500 

##==== When alpha = 0 ==============================================================
summ_true <- summ_strong_alpha0  # true value
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE20_PSBeran_n150.RData")
Results0_PE20_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE20_PSBeran_n300.RData")
Results0_PE20_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE20_PSBeran_n500.RData")
Results0_PE20_n500 <- Getsummary()

load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE35_PSBeran_n150.RData")
Results0_PE35_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE35_PSBeran_n300.RData")
Results0_PE35_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE35_PSBeran_n500.RData")
Results0_PE35_n500 <- Getsummary()

load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE50_PSBeran_n150.RData")
Results0_PE50_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE50_PSBeran_n300.RData")
Results0_PE50_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp0_PE50_PSBeran_n500.RData")
Results0_PE50_n500 <- Getsummary()


race_alp0 <- rbind(c(Results0_PE20_n150$Summary_result[1,4:7], Results0_PE20_n300$Summary_result[1,4:7], Results0_PE20_n500$Summary_result[1,4:7]),
                   c(Results0_PE35_n150$Summary_result[1,4:7], Results0_PE35_n300$Summary_result[1,4:7], Results0_PE35_n500$Summary_result[1,4:7]),
                   c(Results0_PE50_n150$Summary_result[1,4:7], Results0_PE50_n300$Summary_result[1,4:7], Results0_PE50_n500$Summary_result[1,4:7]) )

spce08_alp0 <- rbind(c(Results0_PE20_n150$Summary_result[2,4:7], Results0_PE20_n300$Summary_result[2,4:7], Results0_PE20_n500$Summary_result[2,4:7]),
                     c(Results0_PE35_n150$Summary_result[2,4:7], Results0_PE35_n300$Summary_result[2,4:7], Results0_PE35_n500$Summary_result[2,4:7]),
                     c(Results0_PE50_n150$Summary_result[2,4:7], Results0_PE50_n300$Summary_result[2,4:7], Results0_PE50_n500$Summary_result[2,4:7]) )

spce24_alp0 <- rbind(c(Results0_PE20_n150$Summary_result[3,4:7], Results0_PE20_n300$Summary_result[3,4:7], Results0_PE20_n500$Summary_result[3,4:7]),
                     c(Results0_PE35_n150$Summary_result[3,4:7], Results0_PE35_n300$Summary_result[3,4:7], Results0_PE35_n500$Summary_result[3,4:7]),
                     c(Results0_PE50_n150$Summary_result[3,4:7], Results0_PE50_n300$Summary_result[3,4:7], Results0_PE50_n500$Summary_result[3,4:7]) )

spce_cure_alp0 <- rbind(c(Results0_PE20_n150$Summary_result[4,4:7], Results0_PE20_n300$Summary_result[4,4:7], Results0_PE20_n500$Summary_result[4,4:7]),
                        c(Results0_PE35_n150$Summary_result[4,4:7], Results0_PE35_n300$Summary_result[4,4:7], Results0_PE35_n500$Summary_result[4,4:7]),
                        c(Results0_PE50_n150$Summary_result[4,4:7], Results0_PE50_n300$Summary_result[4,4:7], Results0_PE50_n500$Summary_result[4,4:7]) )

##==== When alpha = 0.5 ========================================================================
summ_true <- summ_strong_alpha05  # true value
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE20_PSBeran_n150.RData")
Results05_PE20_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE20_PSBeran_n300.RData")
Results05_PE20_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE20_PSBeran_n500.RData")
Results05_PE20_n500 <- Getsummary()

load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE35_PSBeran_n150.RData")
Results05_PE35_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE35_PSBeran_n300.RData")
Results05_PE35_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE35_PSBeran_n500.RData")
Results05_PE35_n500 <- Getsummary()

load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE50_PSBeran_n150.RData")
Results05_PE50_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE50_PSBeran_n300.RData")
Results05_PE50_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp05_PE50_PSBeran_n500.RData")
Results05_PE50_n500 <- Getsummary()


race_alp05 <- rbind(c(Results05_PE20_n150$Summary_result[1,4:7], Results05_PE20_n300$Summary_result[1,4:7], Results05_PE20_n500$Summary_result[1,4:7]),
                    c(Results05_PE35_n150$Summary_result[1,4:7], Results05_PE35_n300$Summary_result[1,4:7], Results05_PE35_n500$Summary_result[1,4:7]),
                    c(Results05_PE50_n150$Summary_result[1,4:7], Results05_PE50_n300$Summary_result[1,4:7], Results05_PE50_n500$Summary_result[1,4:7]) )

spce08_alp05 <- rbind(c(Results05_PE20_n150$Summary_result[2,4:7], Results05_PE20_n300$Summary_result[2,4:7], Results05_PE20_n500$Summary_result[2,4:7]),
                      c(Results05_PE35_n150$Summary_result[2,4:7], Results05_PE35_n300$Summary_result[2,4:7], Results05_PE35_n500$Summary_result[2,4:7]),
                      c(Results05_PE50_n150$Summary_result[2,4:7], Results05_PE50_n300$Summary_result[2,4:7], Results05_PE50_n500$Summary_result[2,4:7]) )

spce24_alp05 <- rbind(c(Results05_PE20_n150$Summary_result[3,4:7], Results05_PE20_n300$Summary_result[3,4:7], Results05_PE20_n500$Summary_result[3,4:7]),
                      c(Results05_PE35_n150$Summary_result[3,4:7], Results05_PE35_n300$Summary_result[3,4:7], Results05_PE35_n500$Summary_result[3,4:7]),
                      c(Results05_PE50_n150$Summary_result[3,4:7], Results05_PE50_n300$Summary_result[3,4:7], Results05_PE50_n500$Summary_result[3,4:7]) )

spce_cure_alp05 <- rbind(c(Results05_PE20_n150$Summary_result[4,4:7], Results05_PE20_n300$Summary_result[4,4:7], Results05_PE20_n500$Summary_result[4,4:7]),
                         c(Results05_PE35_n150$Summary_result[4,4:7], Results05_PE35_n300$Summary_result[4,4:7], Results05_PE35_n500$Summary_result[4,4:7]),
                         c(Results05_PE50_n150$Summary_result[4,4:7], Results05_PE50_n300$Summary_result[4,4:7], Results05_PE50_n500$Summary_result[4,4:7]) )

##==== When alpha = 1 ========================================================================
summ_true <- summ_strong_alpha1  # true value
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE20_PSBeran_n150.RData")
Results1_PE20_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE20_PSBeran_n300.RData")
Results1_PE20_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE20_PSBeran_n500.RData")
Results1_PE20_n500 <- Getsummary()


load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE35_PSBeran_n150.RData")
Results1_PE35_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE35_PSBeran_n300.RData")
Results1_PE35_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE35_PSBeran_n500.RData")
Results1_PE35_n500 <- Getsummary()

load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE50_PSBeran_n150.RData")
Results1_PE50_n150 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE50_PSBeran_n300.RData")
Results1_PE50_n300 <- Getsummary()
load("simulation_study/bootstrap_intermediate_results/boots_strong_alp1_PE50_PSBeran_n500.RData")
Results1_PE50_n500 <- Getsummary()


race_alp1 <- rbind( c(Results1_PE20_n150$Summary_result[1,4:7], Results1_PE20_n300$Summary_result[1,4:7], Results1_PE20_n500$Summary_result[1,4:7]),
                    c(Results1_PE35_n150$Summary_result[1,4:7], Results1_PE35_n300$Summary_result[1,4:7], Results1_PE35_n500$Summary_result[1,4:7]),
                    c(Results1_PE50_n150$Summary_result[1,4:7], Results1_PE50_n300$Summary_result[1,4:7], Results1_PE50_n500$Summary_result[1,4:7]) )

spce08_alp1 <- rbind( c(Results1_PE20_n150$Summary_result[2,4:7], Results1_PE20_n300$Summary_result[2,4:7], Results1_PE20_n500$Summary_result[2,4:7]),
                      c(Results1_PE35_n150$Summary_result[2,4:7], Results1_PE35_n300$Summary_result[2,4:7], Results1_PE35_n500$Summary_result[2,4:7]),
                      c(Results1_PE50_n150$Summary_result[2,4:7], Results1_PE50_n300$Summary_result[2,4:7], Results1_PE50_n500$Summary_result[2,4:7]) )

spce24_alp1 <- rbind( c(Results1_PE20_n150$Summary_result[3,4:7], Results1_PE20_n300$Summary_result[3,4:7], Results1_PE20_n500$Summary_result[3,4:7]),
                      c(Results1_PE35_n150$Summary_result[3,4:7], Results1_PE35_n300$Summary_result[3,4:7], Results1_PE35_n500$Summary_result[3,4:7]),
                      c(Results1_PE50_n150$Summary_result[3,4:7], Results1_PE50_n300$Summary_result[3,4:7], Results1_PE50_n500$Summary_result[3,4:7]) )

spce_cure_alp1 <- rbind( c(Results1_PE20_n150$Summary_result[4,4:7], Results1_PE20_n300$Summary_result[4,4:7], Results1_PE20_n500$Summary_result[4,4:7]),
                         c(Results1_PE35_n150$Summary_result[4,4:7], Results1_PE35_n300$Summary_result[4,4:7], Results1_PE35_n500$Summary_result[4,4:7]),
                         c(Results1_PE50_n150$Summary_result[4,4:7], Results1_PE50_n300$Summary_result[4,4:7], Results1_PE50_n500$Summary_result[4,4:7]) )

##==== Summary ===============================================================================
race <- rbind(race_alp0, race_alp05, race_alp1)
row_name <- c("alp0_PE20%", "PE35%", "PE50%", "alp05_PE20%", "PE35%", "PE50%", "alp1_PE20%", "PE35%", "PE50%")
col_name <- c("PB_n150", "SD", "SE", "CP", "PB_n300", "SD", "SE", "CP","PB_n500", "SD", "SE", "CP")
dimnames(race) <- list(row_name, col_name)

spce08 <- rbind(spce08_alp0, spce08_alp05, spce08_alp1)
row_name <- c("alp0_PE20%", "PE35%", "PE50%", "alp05_PE20%", "PE35%", "PE50%", "alp1_PE20%", "PE35%", "PE50%")
col_name <- c("PB_n150", "SD", "SE", "CP", "PB_n300", "SD", "SE", "CP","PB_n500", "SD", "SE", "CP")
dimnames(spce08) <- list(row_name, col_name)

spce24 <- rbind(spce24_alp0, spce24_alp05, spce24_alp1)
row_name <- c("alp0_PE20%", "PE35%", "PE50%", "alp05_PE20%", "PE35%", "PE50%", "alp1_PE20%", "PE35%", "PE50%")
col_name <- c("PB_n150", "SD", "SE", "CP", "PB_n300", "SD", "SE", "CP","PB_n500", "SD", "SE", "CP")
dimnames(spce24) <- list(row_name, col_name)

spce_cure <- rbind(spce_cure_alp0, spce_cure_alp05, spce_cure_alp1)
row_name <- c("alp0_PE20%", "PE35%", "PE50%", "alp05_PE20%", "PE35%", "PE50%", "alp1_PE20%", "PE35%", "PE50%")
col_name <- c("PB_n150", "SD", "SE", "CP", "PB_n300", "SD", "SE", "CP","PB_n500", "SD", "SE", "CP")
dimnames(spce_cure) <- list(row_name, col_name)

Summary_table4 <- list(race = race, 
                       spce08 = spce08, 
                       spce24 = spce24, 
                       spce_cure = spce_cure)

## =============================================================================
## Print Table 4 
## =============================================================================
print(Summary_table4)

#save(Summary_table4, file = "simulation_study/results/table4.RData")


